name: Docker Image CI

on:
  push:
    branches: [ "windbot" ]
  pull_request:
    branches: [ "windbot" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build WindBot
        run: |
          sudo apt install mono-devel -y
          wget -O windbot.zip https://github.com/mycard/windbot/archive/refs/heads/master.zip
          unzip -o -qq windbot.zip
          cd windbot-master/
          xbuild /property:Configuration=Release /property:TargetFrameworkVersion="v4.6"
          mv -f bin/Release ../windbot
          cd ../windbot
          wget -O cards.cdb https://github.com/mycard/ygopro-database/raw/refs/heads/master/locales/zh-CN/cards.cdb

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/windbot:latest
          build-args: |
            WINDBOT_PATH=./windbot
