name: Docker Image CI

on:
  push:
    branches: [ "srvpro2" ]
  pull_request:
    branches: [ "srvpro2" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Data
        run: |
          mkdir -p ygopro
          wget -O ygopro/cards.cdb https://github.com/mycard/ygopro/raw/refs/heads/server/cards.cdb
          wget -O ygopro/lflist.conf https://github.com/mycard/ygopro/raw/refs/heads/server/lflist.conf
          wget -O ocgcore.zip https://github.com/purerosefallen/ygopro-core/archive/refs/heads/master.zip
          wget -O script.zip https://github.com/Fluorohydride/ygopro-scripts/archive/refs/heads/master.zip
          wget -O srvpro.zip https://github.com/purerosefallen/srvpro2/archive/refs/heads/master.zip
          unzip -o -qq ocgcore.zip
          unzip -o -qq script.zip
          unzip -o -qq srvpro.zip
          mv -f ygopro-core-master ygopro/ocgcore
          mv -f ygopro-scripts-master ygopro/script
          mv -f srvpro2-master srvpro
          rm -rf ocgcore.zip script.zip srvpro.zip

      - name: Build OCGCORE
        run: |
          sudo apt-get install -y --no-install-recommends build-essential emscripten uuid-dev
          cp -rf dep/lua ygopro/ocgcore/
          cd ygopro/ocgcore
          wget -O premake5 https://github.com/Unicorn369/ygoserver/releases/download/v0.0.1/premake5-linux-musl
          chmod +x premake5
          cp -rf premake/lua.lua lua/premake5.lua
          ln -sf premake/dll.lua .
          ./premake5 gmake --file=dll.lua --os=emscripten
          make -C build config=release_wasm_cjs -j$(nproc)

      - name: Organize Data
        run: |
          mkdir -p ygoserver
          cp -rf ygopro/ocgcore/build/bin/wasm_cjs/Release/libocgcore.wasm ygoserver/
          rm -rf ygopro/ocgcore
          mv -f ygopro ygoserver/

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/ygoserver
          tags: |
            type=raw,value=srvpro2
            type=raw,value=srvpro2-{{date 'YYYYMMDD'}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SRVPRO_PATH=./srvpro
            YGOPRO_PATH=./ygoserver
            INIT_FILE_PATH=./init.sh
