name: Docker Image CI

on:
  push:
    branches: [ "koishi" ]
  pull_request:
    branches: [ "koishi" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download musl-tools
        run: |
          mkdir -p /opt
          wget -O tools.tar.xz https://github.com/Unicorn369/ygoserver/releases/download/v0.0.1/linux-musl-tools.tar.xz
          tar xf tools.tar.xz
          mv -f linux-musl-tools /opt/
          rm -rf tools.tar.xz
      
      - name: Download Data
        run: |
          wget -O ygopro.zip https://github.com/purerosefallen/ygopro/archive/refs/heads/server.zip
          wget -O ocgcore.zip https://github.com/purerosefallen/ygopro-core/archive/refs/heads/master.zip
          wget -O script.zip https://github.com/Smile-DK/ygopro-scripts/archive/refs/heads/master.zip
          wget -O srvpro.zip https://github.com/purerosefallen/srvpro/archive/refs/heads/master.zip
          unzip -o -qq ygopro.zip
          unzip -o -qq ocgcore.zip
          unzip -o -qq script.zip
          unzip -o -qq srvpro.zip
          mkdir -p ygopro
          mkdir -p ygopro-bin
          mv -f ygopro-server/gframe ygopro/
          mv -f ygopro-server/lflist.conf ygopro/
          mv -f ygopro-server/strings.conf ygopro/
          mv -f ygopro-core-master ocgcore
          mv -f ygopro-scripts-master script
          mv -f srvpro-master srvpro
          rm -rf ygopro-server ygopro.zip ocgcore.zip script.zip srvpro.zip

      - name: Build Ygopro Init
        run: |
          export PATH=$PATH:/opt/linux-musl-tools/bin
          cp -rf dep/* ygopro/
          mv -f ocgcore ygopro/
          mv -f script ygopro/
          cd ygopro/
          premake5 gmake --build-lua --build-event --build-sqlite --server-zip-support
      
      - name: Build Ygopro amd64
        run: |
          export PATH=$PATH:/opt/linux-musl-tools/bin
          export CHOST=x86_64-linux-musl
          export AR=$CHOST-ar
          export CC=$CHOST-cc
          export CXX=$CHOST-c++
          export LD=$CHOST-ld
          export STRIP=$CHOST-strip
          cd ygopro/build/
          rm -rf ../bin/ ../obj/
          make config=release -j$(grep -c "processor" /proc/cpuinfo)
          mv -f ../bin/release/ygopro ../../ygopro-bin/ygopro-amd64
      
      - name: Build Ygopro arm64
        run: |
          export PATH=$PATH:/opt/linux-musl-tools/bin
          export CHOST=aarch64-linux-musl
          export AR=$CHOST-ar
          export CC=$CHOST-cc
          export CXX=$CHOST-c++
          export LD=$CHOST-ld
          export STRIP=$CHOST-strip
          cd ygopro/build/
          rm -rf ../bin/ ../obj/
          make config=release -j$(grep -c "processor" /proc/cpuinfo)
          mv -f ../bin/release/ygopro ../../ygopro-bin/ygopro-arm64
      
      - name: Build Ygopro arm
        run: |
          export PATH=$PATH:/opt/linux-musl-tools/bin
          export CHOST=arm-linux-musleabihf
          export AR=$CHOST-ar
          export CC=$CHOST-cc
          export CXX=$CHOST-c++
          export LD=$CHOST-ld
          export STRIP=$CHOST-strip
          cd ygopro/build/
          rm -rf ../bin/ ../obj/
          make config=release -j$(grep -c "processor" /proc/cpuinfo)
          mv -f ../bin/release/ygopro ../../ygopro-bin/ygopro-arm
      
      - name: Build WindBot
        run: |
          sudo apt install mono-devel -y
          wget -O windbot.zip https://github.com/mycard/windbot/archive/refs/heads/master.zip
          unzip -o -qq windbot.zip
          cd windbot-master/
          xbuild /property:Configuration=Release /property:TargetFrameworkVersion="v4.6"
          mv -f bin/Release ../windbot
          cd .. && rm -rf windbot.zip windbot-master
      
      - name: Organize Data
        run: |
          export PATH=$PATH:/opt/linux-musl-tools/bin
          cp -rf web srvpro/
          cp -rf data-start srvpro/
          x86_64-linux-musl-strip  ygopro-bin/ygopro-amd64
          aarch64-linux-musl-strip ygopro-bin/ygopro-arm64
          arm-linux-musleabihf-strip ygopro-bin/ygopro-arm
          rm -rf windbot/sqlite3.dll
          mv -f windbot srvpro/ && mv -f ygopro srvpro/
          cd srvpro/ygopro/
          rm -rf bin obj build event lua sqlite3 ocgcore
          wget -O cards.cdb https://github.com/mycard/ygopro-database/raw/refs/heads/master/locales/zh-CN/cards.cdb
          ls gframe | sed '/game.cpp/d' | xargs -I {} rm -rf gframe/{}
      
      #
      #- name: Test Data
      #  run: |
      #    wget -O data.zip https://github.com/Unicorn369/ygoserver/releases/download/v0.0.1/data.zip
      #    unzip -o -qq data.zip

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ygoserver:koishi
          build-args: |
            SRVPRO_PATH=./srvpro
            YGOPRO_PATH=./ygopro-bin
            INIT_FILE_PATH=./init.sh
